accounts:
  - name: alice
    coins: ["100000000000000000000uplugcn"]
  - name: bob
    coins: ["5000000000000uplugcn"]
validator:
  name: alice
  staked: "100000000000000000000uplugcn"
faucet:
  name: bob 
  coins: ["10uplugcn"]
build:
  binary: "plugchaind"
init:
  home: "$HOME/.plugchaind"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "plugchaind_520-1"
  app_state:
    staking:
      params:
        bond_denom: "uplugcn"
    mint:
      params:
        mint_denom: "uplugcn"
    crisis:
      constant_fee:
        denom: "uplugcn"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "uplugcn"
    evm:
      params:
        evm_denom: "uplugcn"
    oracle:
      params:
        claim_params:
          AtomClaim: # This is our oracle 'type'
            vote_period: 3 # Voting round duration in blocks
            claim_type: 'AtomClaim' # Oracle type again
            prevote: true # Require commit-reveal type voting to avoid free-rider problem
            vote_threshold: '0.5' # Validator power threshold required to reach consensus
