version: '3'

services:
  plugchain_node0:
    container_name: plugchain_node0
    image: "plugchain"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - CHAINID=plugchain_521-1
      - ID=0
      - LOG=${LOG:-plugchaind.log}
      - GENESIS=true
    volumes:
      - ../plugchain:/plugchain
    networks:
      localnet:
        ipv4_address: 192.17.10.2
    build:
      context: ./
      dockerfile: Dockerfile
    command: './scripts/setup-docker.sh'
<<<<<<< HEAD
=======
    tty: true
>>>>>>> d79323fb0f7dd4dd7b9baf4a27f51c8e5ac75472

  plugchain_node1:
    depends_on:
      - plugchain_node0
    container_name: plugchain_node1
    image: "plugchain"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - CHAINID=plugchain_521-1
      - ID=1
      - LOG=${LOG:-plugchaind.log}
      - GENESIS=false
      - CONNECTIP=192.17.10.2:26656
    volumes:
      - ../plugchain:/plugchain
    networks:
      localnet:
        ipv4_address: 192.17.10.3
<<<<<<< HEAD
    # command: './scripts/setup-docker.sh'
=======
    command: './scripts/setup-docker.sh'
>>>>>>> d79323fb0f7dd4dd7b9baf4a27f51c8e5ac75472
    tty: true

  plugchain_node2:
    depends_on:
      - plugchain_node0
    container_name: plugchain_node2
    image: "plugchain"
    environment:
      - CHAINID=plugchain_521-1
      - ID=2
      - LOG=${LOG:-plugchaind.log}
      - GENESIS=false
      - CONNECTIP=192.17.10.2:26656
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ../plugchain:/plugchain
    networks:
      localnet:
        ipv4_address: 192.17.10.4
    command: './scripts/setup-docker.sh'
<<<<<<< HEAD
=======
    tty: true
>>>>>>> d79323fb0f7dd4dd7b9baf4a27f51c8e5ac75472

  plugchain_node3:
    depends_on:
      - plugchain_node0
    container_name: plugchain_node3
    image: "plugchain"
    environment:
      - CHAINID=plugchain_521-1
      - ID=3
      - LOG=${LOG:-plugchaind.log}
      - GENESIS=false
      - CONNECTIP=192.17.10.2:26656
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ../plugchain:/plugchain
    networks:
      localnet:
        ipv4_address: 192.17.10.5
    command: './scripts/setup-docker.sh'
<<<<<<< HEAD
=======
    tty: true
>>>>>>> d79323fb0f7dd4dd7b9baf4a27f51c8e5ac75472

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.17.10.0/16

