// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: onp/plugchain/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryTokenListRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTokenListRequest) Reset()         { *m = QueryTokenListRequest{} }
func (m *QueryTokenListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTokenListRequest) ProtoMessage()    {}
func (*QueryTokenListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca22e1f3193bc40f, []int{0}
}
func (m *QueryTokenListRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTokenListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTokenListRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTokenListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTokenListRequest.Merge(m, src)
}
func (m *QueryTokenListRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTokenListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTokenListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTokenListRequest proto.InternalMessageInfo

func (m *QueryTokenListRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryTokenListResponse struct {
	Tokens     []MsgCreateToken    `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTokenListResponse) Reset()         { *m = QueryTokenListResponse{} }
func (m *QueryTokenListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTokenListResponse) ProtoMessage()    {}
func (*QueryTokenListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca22e1f3193bc40f, []int{1}
}
func (m *QueryTokenListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTokenListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTokenListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTokenListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTokenListResponse.Merge(m, src)
}
func (m *QueryTokenListResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTokenListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTokenListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTokenListResponse proto.InternalMessageInfo

func (m *QueryTokenListResponse) GetTokens() []MsgCreateToken {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *QueryTokenListResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryTokensByAccAddrRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryTokensByAccAddrRequest) Reset()         { *m = QueryTokensByAccAddrRequest{} }
func (m *QueryTokensByAccAddrRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTokensByAccAddrRequest) ProtoMessage()    {}
func (*QueryTokensByAccAddrRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca22e1f3193bc40f, []int{2}
}
func (m *QueryTokensByAccAddrRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTokensByAccAddrRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTokensByAccAddrRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTokensByAccAddrRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTokensByAccAddrRequest.Merge(m, src)
}
func (m *QueryTokensByAccAddrRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTokensByAccAddrRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTokensByAccAddrRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTokensByAccAddrRequest proto.InternalMessageInfo

func (m *QueryTokensByAccAddrRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryTokensByAccAddrResponse struct {
	Token []MsgCreateToken `protobuf:"bytes,1,rep,name=token,proto3" json:"token"`
}

func (m *QueryTokensByAccAddrResponse) Reset()         { *m = QueryTokensByAccAddrResponse{} }
func (m *QueryTokensByAccAddrResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTokensByAccAddrResponse) ProtoMessage()    {}
func (*QueryTokensByAccAddrResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca22e1f3193bc40f, []int{3}
}
func (m *QueryTokensByAccAddrResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTokensByAccAddrResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTokensByAccAddrResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTokensByAccAddrResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTokensByAccAddrResponse.Merge(m, src)
}
func (m *QueryTokensByAccAddrResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTokensByAccAddrResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTokensByAccAddrResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTokensByAccAddrResponse proto.InternalMessageInfo

func (m *QueryTokensByAccAddrResponse) GetToken() []MsgCreateToken {
	if m != nil {
		return m.Token
	}
	return nil
}

type QueryTokenInfoRequest struct {
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (m *QueryTokenInfoRequest) Reset()         { *m = QueryTokenInfoRequest{} }
func (m *QueryTokenInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTokenInfoRequest) ProtoMessage()    {}
func (*QueryTokenInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca22e1f3193bc40f, []int{4}
}
func (m *QueryTokenInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTokenInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTokenInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTokenInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTokenInfoRequest.Merge(m, src)
}
func (m *QueryTokenInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTokenInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTokenInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTokenInfoRequest proto.InternalMessageInfo

func (m *QueryTokenInfoRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type QueryTokenInfoResponse struct {
	Token MsgCreateToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
}

func (m *QueryTokenInfoResponse) Reset()         { *m = QueryTokenInfoResponse{} }
func (m *QueryTokenInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTokenInfoResponse) ProtoMessage()    {}
func (*QueryTokenInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca22e1f3193bc40f, []int{5}
}
func (m *QueryTokenInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTokenInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTokenInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTokenInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTokenInfoResponse.Merge(m, src)
}
func (m *QueryTokenInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTokenInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTokenInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTokenInfoResponse proto.InternalMessageInfo

func (m *QueryTokenInfoResponse) GetToken() MsgCreateToken {
	if m != nil {
		return m.Token
	}
	return MsgCreateToken{}
}

func init() {
	proto.RegisterType((*QueryTokenListRequest)(nil), "onp.plugchain.v1.QueryTokenListRequest")
	proto.RegisterType((*QueryTokenListResponse)(nil), "onp.plugchain.v1.QueryTokenListResponse")
	proto.RegisterType((*QueryTokensByAccAddrRequest)(nil), "onp.plugchain.v1.QueryTokensByAccAddrRequest")
	proto.RegisterType((*QueryTokensByAccAddrResponse)(nil), "onp.plugchain.v1.QueryTokensByAccAddrResponse")
	proto.RegisterType((*QueryTokenInfoRequest)(nil), "onp.plugchain.v1.QueryTokenInfoRequest")
	proto.RegisterType((*QueryTokenInfoResponse)(nil), "onp.plugchain.v1.QueryTokenInfoResponse")
}

func init() { proto.RegisterFile("onp/plugchain/v1/query.proto", fileDescriptor_ca22e1f3193bc40f) }

var fileDescriptor_ca22e1f3193bc40f = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x33, 0xad, 0x8d, 0x74, 0x7a, 0x50, 0x06, 0x2d, 0x21, 0xc6, 0x35, 0x2c, 0x6a, 0xe2,
	0xa1, 0x33, 0x24, 0x1e, 0xbc, 0x14, 0xa1, 0x11, 0x14, 0x41, 0xa5, 0x06, 0xe9, 0x41, 0x84, 0x30,
	0xbb, 0x99, 0x6e, 0x97, 0x6e, 0xe6, 0x6d, 0x77, 0x26, 0xd1, 0x50, 0x7a, 0x11, 0xaf, 0x82, 0xe0,
	0x27, 0xe8, 0x57, 0xf1, 0xd4, 0x63, 0xc1, 0x8b, 0x27, 0x91, 0xc4, 0x0f, 0x22, 0x3b, 0xbb, 0xdb,
	0x6e, 0x93, 0x34, 0x35, 0xb7, 0x9d, 0x7d, 0xf3, 0x7f, 0xef, 0xf7, 0xfe, 0xef, 0x31, 0xb8, 0x02,
	0x32, 0x64, 0x61, 0xd0, 0xf7, 0xdc, 0x3d, 0xee, 0x4b, 0x36, 0x68, 0xb0, 0x83, 0xbe, 0x88, 0x86,
	0x34, 0x8c, 0x40, 0x03, 0xb9, 0x09, 0x32, 0xa4, 0x67, 0x51, 0x3a, 0x68, 0x94, 0x6f, 0x79, 0xe0,
	0x81, 0x09, 0xb2, 0xf8, 0x2b, 0xb9, 0x57, 0xae, 0x78, 0x00, 0x5e, 0x20, 0x18, 0x0f, 0x7d, 0xc6,
	0xa5, 0x04, 0xcd, 0xb5, 0x0f, 0x52, 0xa5, 0xd1, 0xbb, 0x2e, 0xa8, 0x1e, 0xa8, 0x4e, 0x22, 0x0b,
	0xb9, 0xe7, 0x4b, 0x13, 0xcf, 0xc4, 0x53, 0x08, 0x1a, 0xf6, 0x45, 0x1a, 0xb5, 0x3b, 0xf8, 0xf6,
	0xdb, 0x98, 0xe8, 0x5d, 0xfc, 0xef, 0x95, 0xaf, 0x74, 0x5b, 0x1c, 0xf4, 0x85, 0xd2, 0xe4, 0x39,
	0xc6, 0xe7, 0xa9, 0x4a, 0xa8, 0x8a, 0xea, 0x6b, 0xcd, 0x87, 0x34, 0x29, 0x45, 0x1d, 0xae, 0x04,
	0x4d, 0x3a, 0x19, 0x34, 0x1c, 0xa1, 0x79, 0x83, 0x6e, 0x73, 0x4f, 0xa4, 0xda, 0x76, 0x4e, 0x69,
	0x1f, 0x23, 0xbc, 0x3e, 0x59, 0x41, 0x85, 0x20, 0x95, 0x20, 0x4f, 0x71, 0xd1, 0xa0, 0xa8, 0x12,
	0xaa, 0x2e, 0xd7, 0xd7, 0x9a, 0x55, 0x3a, 0xe9, 0x07, 0x7d, 0xad, 0xbc, 0x67, 0x91, 0xe0, 0x5a,
	0x18, 0x75, 0xeb, 0xda, 0xc9, 0xef, 0x7b, 0x85, 0x76, 0xaa, 0x22, 0x2f, 0x2e, 0x20, 0x2e, 0x19,
	0xc4, 0xda, 0x95, 0x88, 0x49, 0xf1, 0x0b, 0x8c, 0x4f, 0xf0, 0x9d, 0x73, 0x44, 0xd5, 0x1a, 0x6e,
	0xb9, 0xee, 0x56, 0xb7, 0x1b, 0x65, 0x56, 0x94, 0xf0, 0x75, 0xde, 0xed, 0x46, 0x42, 0x29, 0xe3,
	0xc3, 0x6a, 0x3b, 0x3b, 0xda, 0x1f, 0x70, 0x65, 0xb6, 0x30, 0xed, 0x70, 0x13, 0xaf, 0x18, 0xd6,
	0x05, 0x1b, 0x4c, 0x44, 0x36, 0xcb, 0xcf, 0xe6, 0xa5, 0xdc, 0x85, 0x0c, 0x68, 0x1d, 0x17, 0xd5,
	0xb0, 0xe7, 0x40, 0x90, 0xf2, 0xa4, 0x27, 0x7b, 0x27, 0x6f, 0x75, 0x22, 0x98, 0x06, 0x41, 0x0b,
	0x83, 0x34, 0x7f, 0x2c, 0xe3, 0x15, 0x93, 0x98, 0x7c, 0x41, 0x78, 0xf5, 0x6c, 0x90, 0xa4, 0x36,
	0x9d, 0x66, 0xe6, 0x32, 0x95, 0xeb, 0x57, 0x5f, 0x4c, 0x40, 0xed, 0xfb, 0x9f, 0x7f, 0xfe, 0xfd,
	0xbe, 0x64, 0x91, 0x0a, 0x9b, 0xbd, 0xb6, 0x9d, 0x20, 0x2e, 0x7c, 0x8c, 0xf0, 0x8d, 0x09, 0xcf,
	0xc9, 0xc6, 0xbc, 0x1a, 0x53, 0x43, 0x2d, 0xd3, 0xff, 0xbd, 0x9e, 0x82, 0x31, 0x03, 0xf6, 0x88,
	0xd4, 0x2e, 0x01, 0x53, 0x9d, 0x78, 0x29, 0xd8, 0x61, 0xba, 0x1a, 0x47, 0xe4, 0x6b, 0x66, 0x55,
	0x3c, 0x88, 0xf9, 0x56, 0xe5, 0x66, 0x3b, 0xdf, 0xaa, 0xfc, 0x4c, 0xed, 0x0d, 0x43, 0x54, 0x23,
	0x0f, 0x2e, 0xb3, 0xca, 0x97, 0xbb, 0xc0, 0x0e, 0x93, 0xdd, 0x38, 0x6a, 0xed, 0x9c, 0x8c, 0x2c,
	0x74, 0x3a, 0xb2, 0xd0, 0x9f, 0x91, 0x85, 0xbe, 0x8d, 0xad, 0xc2, 0xe9, 0xd8, 0x2a, 0xfc, 0x1a,
	0x5b, 0x85, 0xf7, 0x9b, 0x9e, 0xaf, 0xf7, 0xfa, 0x0e, 0x75, 0xa1, 0xc7, 0x20, 0xe2, 0x6e, 0x20,
	0xde, 0x08, 0xfd, 0x11, 0xa2, 0xfd, 0xed, 0xf8, 0x89, 0x70, 0x21, 0xc8, 0x25, 0xff, 0x94, 0xfb,
	0xd6, 0xc3, 0x50, 0x28, 0xa7, 0x68, 0x1e, 0x92, 0xc7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe0,
	0xf6, 0x36, 0x75, 0xeb, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	TokenList(ctx context.Context, in *QueryTokenListRequest, opts ...grpc.CallOption) (*QueryTokenListResponse, error)
	TokensByAccAddr(ctx context.Context, in *QueryTokensByAccAddrRequest, opts ...grpc.CallOption) (*QueryTokensByAccAddrResponse, error)
	TokenInfo(ctx context.Context, in *QueryTokenInfoRequest, opts ...grpc.CallOption) (*QueryTokenInfoResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) TokenList(ctx context.Context, in *QueryTokenListRequest, opts ...grpc.CallOption) (*QueryTokenListResponse, error) {
	out := new(QueryTokenListResponse)
	err := c.cc.Invoke(ctx, "/onp.plugchain.v1.Query/TokenList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TokensByAccAddr(ctx context.Context, in *QueryTokensByAccAddrRequest, opts ...grpc.CallOption) (*QueryTokensByAccAddrResponse, error) {
	out := new(QueryTokensByAccAddrResponse)
	err := c.cc.Invoke(ctx, "/onp.plugchain.v1.Query/TokensByAccAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TokenInfo(ctx context.Context, in *QueryTokenInfoRequest, opts ...grpc.CallOption) (*QueryTokenInfoResponse, error) {
	out := new(QueryTokenInfoResponse)
	err := c.cc.Invoke(ctx, "/onp.plugchain.v1.Query/TokenInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	TokenList(context.Context, *QueryTokenListRequest) (*QueryTokenListResponse, error)
	TokensByAccAddr(context.Context, *QueryTokensByAccAddrRequest) (*QueryTokensByAccAddrResponse, error)
	TokenInfo(context.Context, *QueryTokenInfoRequest) (*QueryTokenInfoResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) TokenList(ctx context.Context, req *QueryTokenListRequest) (*QueryTokenListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenList not implemented")
}
func (*UnimplementedQueryServer) TokensByAccAddr(ctx context.Context, req *QueryTokensByAccAddrRequest) (*QueryTokensByAccAddrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokensByAccAddr not implemented")
}
func (*UnimplementedQueryServer) TokenInfo(ctx context.Context, req *QueryTokenInfoRequest) (*QueryTokenInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenInfo not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_TokenList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTokenListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TokenList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onp.plugchain.v1.Query/TokenList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TokenList(ctx, req.(*QueryTokenListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TokensByAccAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTokensByAccAddrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TokensByAccAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onp.plugchain.v1.Query/TokensByAccAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TokensByAccAddr(ctx, req.(*QueryTokensByAccAddrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onp.plugchain.v1.Query/TokenInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TokenInfo(ctx, req.(*QueryTokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onp.plugchain.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TokenList",
			Handler:    _Query_TokenList_Handler,
		},
		{
			MethodName: "TokensByAccAddr",
			Handler:    _Query_TokensByAccAddr_Handler,
		},
		{
			MethodName: "TokenInfo",
			Handler:    _Query_TokenInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "onp/plugchain/v1/query.proto",
}

func (m *QueryTokenListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTokenListRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTokenListRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTokenListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTokenListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTokenListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Tokens) > 0 {
		for iNdEx := len(m.Tokens) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tokens[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryTokensByAccAddrRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTokensByAccAddrRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTokensByAccAddrRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTokensByAccAddrResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTokensByAccAddrResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTokensByAccAddrResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Token) > 0 {
		for iNdEx := len(m.Token) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Token[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryTokenInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTokenInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTokenInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTokenInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTokenInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTokenInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Token.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryTokenListRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTokenListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Tokens) > 0 {
		for _, e := range m.Tokens {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTokensByAccAddrRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTokensByAccAddrResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Token) > 0 {
		for _, e := range m.Token {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryTokenInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTokenInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Token.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryTokenListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTokenListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTokenListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTokenListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTokenListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTokenListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tokens = append(m.Tokens, MsgCreateToken{})
			if err := m.Tokens[len(m.Tokens)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTokensByAccAddrRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTokensByAccAddrRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTokensByAccAddrRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTokensByAccAddrResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTokensByAccAddrResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTokensByAccAddrResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = append(m.Token, MsgCreateToken{})
			if err := m.Token[len(m.Token)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTokenInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTokenInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTokenInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTokenInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTokenInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTokenInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Token.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
